/**
 * Contract ABIs for ZeroID protocol interactions.
 *
 * Minimal ABI definitions for the functions the frontend needs to call.
 * Full ABIs are generated by Hardhat compilation in the contracts/ directory.
 */

// ---------------------------------------------------------------------------
// IdentityRegistry
// ---------------------------------------------------------------------------

export const IdentityRegistryABI = [
  // --- Read Functions ---
  {
    name: "resolveIdentity",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "didHash", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "didHash", type: "bytes32" },
          { name: "controller", type: "address" },
          { name: "createdAt", type: "uint64" },
          { name: "updatedAt", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "recoveryHash", type: "bytes32" },
          { name: "credentialCount", type: "uint32" },
          { name: "nonce", type: "uint32" },
        ],
      },
    ],
  },
  {
    name: "isActiveIdentity",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "didHash", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Write Functions ---
  {
    name: "registerIdentity",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "didHash", type: "bytes32" },
      { name: "recoveryHash", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    name: "updateIdentityStatus",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "didHash", type: "bytes32" },
      { name: "newStatus", type: "uint8" },
    ],
    outputs: [],
  },
  {
    name: "changeController",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "didHash", type: "bytes32" },
      { name: "newController", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "initiateRecovery",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "didHash", type: "bytes32" },
      { name: "recoveryProof", type: "bytes32" },
      { name: "newController", type: "address" },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: "IdentityRegistered",
    type: "event",
    inputs: [
      { name: "didHash", type: "bytes32", indexed: true },
      { name: "controller", type: "address", indexed: true },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
  {
    name: "IdentityUpdated",
    type: "event",
    inputs: [
      { name: "didHash", type: "bytes32", indexed: true },
      { name: "newStatus", type: "uint8", indexed: false },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
  {
    name: "ControllerChanged",
    type: "event",
    inputs: [
      { name: "didHash", type: "bytes32", indexed: true },
      { name: "oldController", type: "address", indexed: true },
      { name: "newController", type: "address", indexed: true },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// CredentialRegistry
// ---------------------------------------------------------------------------

export const CredentialRegistryABI = [
  // --- Read Functions ---
  {
    name: "getCredential",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "credentialHash", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "credentialHash", type: "bytes32" },
          { name: "schemaHash", type: "bytes32" },
          { name: "issuerDid", type: "bytes32" },
          { name: "subjectDid", type: "bytes32" },
          { name: "issuedAt", type: "uint64" },
          { name: "expiresAt", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "merkleRoot", type: "bytes32" },
        ],
      },
    ],
  },
  {
    name: "isCredentialValid",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "credentialHash", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Write Functions ---
  {
    name: "issueCredential",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "credentialHash", type: "bytes32" },
      { name: "schemaHash", type: "bytes32" },
      { name: "subjectDid", type: "bytes32" },
      { name: "expiresAt", type: "uint64" },
      { name: "merkleRoot", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    name: "revokeCredential",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "credentialHash", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "suspendCredential",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "credentialHash", type: "bytes32" }],
    outputs: [],
  },
  {
    name: "reinstateCredential",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "credentialHash", type: "bytes32" }],
    outputs: [],
  },

  // --- Events ---
  {
    name: "CredentialIssued",
    type: "event",
    inputs: [
      { name: "credentialHash", type: "bytes32", indexed: true },
      { name: "issuerDid", type: "bytes32", indexed: true },
      { name: "subjectDid", type: "bytes32", indexed: true },
    ],
  },
  {
    name: "CredentialRevoked",
    type: "event",
    inputs: [
      { name: "credentialHash", type: "bytes32", indexed: true },
      { name: "issuerDid", type: "bytes32", indexed: true },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// ZKVerifier
// ---------------------------------------------------------------------------

export const ZKVerifierABI = [
  // --- Read Functions ---
  {
    name: "verifyProof",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "circuitId", type: "bytes32" },
      {
        name: "proof",
        type: "tuple",
        components: [
          { name: "a", type: "uint256[2]" },
          { name: "b", type: "uint256[2][2]" },
          { name: "c", type: "uint256[2]" },
        ],
      },
      { name: "publicInputs", type: "uint256[]" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "isCircuitRegistered",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "circuitId", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Write Functions ---
  {
    name: "setVerificationKey",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "circuitId", type: "bytes32" },
      { name: "alpha", type: "uint256[2]" },
      { name: "beta", type: "uint256[2][2]" },
      { name: "gamma", type: "uint256[2][2]" },
      { name: "delta", type: "uint256[2][2]" },
      { name: "ic", type: "uint256[2][]" },
    ],
    outputs: [],
  },

  // --- Events ---
  {
    name: "ProofVerified",
    type: "event",
    inputs: [
      { name: "proofHash", type: "bytes32", indexed: true },
      { name: "credentialHash", type: "bytes32", indexed: true },
      { name: "valid", type: "bool", indexed: false },
    ],
  },
  {
    name: "VerificationKeyUpdated",
    type: "event",
    inputs: [
      { name: "circuitId", type: "bytes32", indexed: true },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// TEEAttestation
// ---------------------------------------------------------------------------

export const TEEAttestationABI = [
  // --- Read Functions ---
  {
    name: "isAttestationValid",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "enclaveHash", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getAttestation",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "enclaveHash", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "enclaveHash", type: "bytes32" },
          { name: "platform", type: "uint8" },
          { name: "attestedAt", type: "uint64" },
          { name: "expiresAt", type: "uint64" },
          { name: "reportDataHash", type: "bytes32" },
          { name: "nodeOperator", type: "address" },
          { name: "isValid", type: "bool" },
        ],
      },
    ],
  },

  // --- Write Functions ---
  {
    name: "submitAttestation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "enclaveHash", type: "bytes32" },
      { name: "platform", type: "uint8" },
      { name: "reportDataHash", type: "bytes32" },
      { name: "attestationSignature", type: "bytes" },
      { name: "validityDuration", type: "uint64" },
    ],
    outputs: [],
  },
  {
    name: "revokeAttestation",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "enclaveHash", type: "bytes32" }],
    outputs: [],
  },

  // --- Events ---
  {
    name: "AttestationSubmitted",
    type: "event",
    inputs: [
      { name: "enclaveHash", type: "bytes32", indexed: true },
      { name: "platform", type: "uint8", indexed: false },
      { name: "nodeOperator", type: "address", indexed: true },
    ],
  },
  {
    name: "AttestationRevoked",
    type: "event",
    inputs: [
      { name: "enclaveHash", type: "bytes32", indexed: true },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// SelectiveDisclosure
// ---------------------------------------------------------------------------

export const SelectiveDisclosureABI = [
  // --- Read Functions ---
  {
    name: "getDisclosureResult",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "requestId", type: "bytes32" }],
    outputs: [
      { name: "verified", type: "bool" },
      { name: "verifiedAt", type: "uint64" },
    ],
  },

  // --- Write Functions ---
  {
    name: "createDisclosureRequest",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "subjectDid", type: "bytes32" },
      { name: "credentialHash", type: "bytes32" },
      { name: "attributeHashes", type: "bytes32[]" },
      { name: "expiresAt", type: "uint64" },
    ],
    outputs: [{ name: "requestId", type: "bytes32" }],
  },
  {
    name: "submitDisclosureProof",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "requestId", type: "bytes32" },
      { name: "circuitId", type: "bytes32" },
      {
        name: "proof",
        type: "tuple",
        components: [
          { name: "a", type: "uint256[2]" },
          { name: "b", type: "uint256[2][2]" },
          { name: "c", type: "uint256[2]" },
        ],
      },
      { name: "publicInputs", type: "uint256[]" },
      { name: "merkleProof", type: "bytes32[]" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Events ---
  {
    name: "DisclosureRequested",
    type: "event",
    inputs: [
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "subjectDid", type: "bytes32", indexed: true },
      { name: "attributeHashes", type: "bytes32[]", indexed: false },
    ],
  },
  {
    name: "DisclosureProofSubmitted",
    type: "event",
    inputs: [
      { name: "requestId", type: "bytes32", indexed: true },
      { name: "verified", type: "bool", indexed: false },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// GovernanceModule
// ---------------------------------------------------------------------------

export const GovernanceModuleABI = [
  // --- Read Functions ---
  {
    name: "getProposalState",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "isApprovedSchema",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "schemaHash", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "isApprovedIssuer",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "issuerDid", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Write Functions ---
  {
    name: "proposeSchema",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "schemaHash", type: "bytes32" },
      { name: "name", type: "string" },
      { name: "attributeHashes", type: "bytes32[]" },
    ],
    outputs: [{ name: "proposalId", type: "uint256" }],
  },
  {
    name: "proposeIssuer",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "issuerDid", type: "bytes32" }],
    outputs: [{ name: "proposalId", type: "uint256" }],
  },
  {
    name: "castVote",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "support", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "executeProposal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "cancelProposal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },

  // --- Events ---
  {
    name: "SchemaProposed",
    type: "event",
    inputs: [
      { name: "schemaHash", type: "bytes32", indexed: true },
      { name: "proposer", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
    ],
  },
  {
    name: "SchemaApproved",
    type: "event",
    inputs: [
      { name: "schemaHash", type: "bytes32", indexed: true },
      { name: "timestamp", type: "uint64", indexed: false },
    ],
  },
  {
    name: "ProposalCreated",
    type: "event",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "proposer", type: "address", indexed: true },
      { name: "targetHash", type: "bytes32", indexed: true },
    ],
  },
  {
    name: "VoteCast",
    type: "event",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "voter", type: "address", indexed: true },
      { name: "support", type: "bool", indexed: false },
      { name: "weight", type: "uint256", indexed: false },
    ],
  },
] as const;
